# process_data.R -
#
#   takes data generated by cleanup_germination_data.R and estimates germination times.
#   germination times will be written to germination-{perssed,pergroup}.tsv in the data folder.

library(dplyr)
library(pracma)

# there is no support for directory picker under non-windows platforms
if (.Platform$OS.type == 'unix') {
  dir <- readline(prompt = "Enter directory containing output.csv: ")
} else {
  dir <- choose.dir(getwd(), "Choose folder containing output.csv")
}

data <- read.table(paste0(dir, "/output.tsv"), header=T)

data$dperim <- data$pav <- groups <- uids <- perims <- NULL

# algorithm works like this:
# for each seed, calculate a moving average of the perimeter to reduce noise (called pav).
# then, calculate a change in perimeter compared to the average value of the first three frames (called dperim).
# after we do this, we can select the value where dperim is larger than 1.04, which signifies germination.
for(group in unique(data$Group)) {
  for(uid in unique(data$UID[data$Group == group])) {
    data$pav[data$Group==group & data$UID==uid] <- movavg(data$`Perim.`[data$Group==group & data$UID==uid], n=3, t='s')
    data$dperim[data$Group==group & data$UID==uid] <- data$pav[data$Group==group & data$UID==uid] / mean(c(perims, data$`Perim.`[data$Group==group & data$UID==uid][1:3]))
    # ignore the first three frames (moving average requires three frames)
    data$dperim[data$Group==group & data$UID==uid][1:3] <- 1
  }
}

data.peruid <- data %>% 
  group_by(Group, UID) %>%
  filter(dperim > 1.04) %>%
  arrange(ElapsedHours) %>%
  summarize(GerminationTime = ElapsedHours[1], GerminationSlice = Slice[1])

data.pergroup <- data.peruid %>%
  group_by(Group) %>%
  summarize(GerminationTimeSD = sd(GerminationTime,na.rm=T), GerminationTime = mean(GerminationTime))

write.table(data.peruid, file=paste0(dir, "/germination-perseed.tsv"), sep='\t', row.names=F)
write.table(data.pergroup, file=paste0(dir, "/germination-pergroup.tsv"), sep='\t', row.names=F)
