# process_data.R -
#
#   takes data generated by cleanup_germination_data.R and estimates germination times.
#   germination times will be written to germination-perseed.tsv and germinationstats.tsv in the data folder.
#   additionally, a graph indicating germination progression is written for each group.

library(dplyr)
library(reshape2)
library(germinationmetrics)
library(zoo)

# TUNABLES:
# lookahead_slices:
#   germination is determined as the point where the seed perimeter is increasing for <lookahead_slices> 
#   number of slices. default is 10.
lookahead_slices <- 10

# there is no support for directory picker under non-windows platforms
# there is no support for directory picker under non-windows platforms
if (.Platform$OS.type == 'unix') {
  dir <- readline(prompt = "Enter directory: ")
} else {
  dir <- choose.dir(getwd(), "Choose folder to process")
}

resultsdir <- paste0(dir, '/Results')
outdir <- paste0(resultsdir, '/Germination assay')

# set up output dir
if (dir.exists(paste0(outdir, '/Analysis output'))) {
  runs <- list.dirs(paste0(outdir, '/Analysis output'), full.names=F, recursive=F)
  runs <- as.numeric(runs)
  run_number <- max(runs) + 1
  if (run_number < 1) {
    run_number <- 1
  }
} else {
  dir.create(paste0(outdir, '/Analysis output'), recursive=T)
  run_number <- 1
}

rundir <- paste0(outdir, '/Analysis output/', run_number)
dir.create(rundir, showWarnings=F)

cat("Processing germination data. This will take a little while...\n")

data <- read.table(paste0(outdir, "/germination.postQC.tsv"), header=T)

# copy postQC input file to rundir for reference
file.copy(paste0(outdir, "/germination.postQC.tsv"), rundir)

data$dPerim <- data$ddPerim <- 0
data$Germinated <- 0
data$pav <- groups <- uids <- perims <- NULL

for(uid in unique(data$UID)) {
  # ds = data subset
  ds <- subset(data, UID == uid)
  
  if (nrow(ds) < lookahead_slices + 4) {
    cat(paste0("Too few data points for UID ", uid, ", removing from analysis.\n"))
    next
  }

  # seed size is average of first 5 slices
  seedsize <- mean(ds$`Perim.`[1:5])
  
  # create moving average perimeter increase (dPerim)
  ds$dPerim <- rollapply(ds$`Perim.`, 5, mean, na.rm=T, align="left", partial=FALSE, fill=NA)
  ds$dPerim <- ds$dPerim - seedsize
  
  # set delta delta perimeter (rate of change of perimeter)
  ds$ddPerim[2:nrow(ds)] <- ds$dPerim[2:nrow(ds)] - ds$dPerim[1:nrow(ds) - 1]
  ds$ddPerim[1] <- 0
  
  # loop over the values again...:\
  # we need a buffer of (4 + lookahead_slices) slices.
  for (i in seq(1, nrow(ds) - (4 + lookahead_slices))) {
    if (ds$dPerim[i] > 0) {
      if (all(ds$ddPerim[seq(i + 1, i + lookahead_slices)] > 0)) {
        ds$Germinated[i] <- TRUE
        break
      }
    }
  }
  
  # replace the data with the manipulated subset
  data <- subset(data, UID != uid)
  data <- rbind(data, ds)
}

data.peruid <- data %>% 
  group_by(Group, UID) %>%
  filter(Germinated == 1) %>%
  arrange(ElapsedHours) %>%
  summarize(GerminationTime = ElapsedHours[1], GerminationSlice = Slice[1])

data.peruid <- as.data.frame(data.peruid)

uids <- unique(data$UID)
uids <- uids[order(uids)]
included <- uids %in% data.peruid$UID
for(uid in uids[!included]) {
  group <- data$Group[data$UID == uid][1]
  row = data.frame(Group = group, UID = uid, GerminationTime = NA, GerminationSlice = NA)
  data.peruid <- rbind(data.peruid, row)
}

# sort data naturally
m<-regexpr('([0-9]+)$', data.peruid$UID)
data.peruid$num <- as.numeric(regmatches(data.peruid$UID, m))
data.peruid <- data.peruid[order(data.peruid$Group, data.peruid$num),]
data.peruid <- data.peruid %>% select(-num)

names(data.peruid)[3] <- 'Germination Time (h)'
names(data.peruid)[4] <- 'Germination detected on frame'
write.table(data.peruid, file=paste0(rundir, "/germination-perseed.tsv"), sep='\t', row.names=F)

# merge group and uid so we can keep both in the conversion long->wide->long
data$GroupUID<-paste(data$Group, data$UID, sep="!")

# convert to wide and back again as a hacky way of making sure all seeds have equal number of slices
data.wide <- dcast(data, Slice ~ GroupUID, value.var = "Germinated")
data.long <- melt(data.wide, id.vars="Slice")

# now get all the groups and uids back
groupuids <- unlist(strsplit(as.character(data.long$variable), "!"))
data.long$Group <- groupuids[seq(1, length(groupuids), 2)]
data.long$UID <- groupuids[seq(2, length(groupuids), 2)]
data.long$value[is.na(data.long$value)] <- 0

# calculate germination stats
germstats <- data.long %>% 
  group_by(Group, Slice) %>% 
  summarize(GermCount = sum(value))

germstats <- germstats %>% 
  group_by(Group) %>%
  arrange(Slice) %>%
  mutate(CumGermCount = cumsum(GermCount))

# to get the intervals in hours, we calculate average time per slice and multiply
# slice# by that values. this will hopefully be good enough approximation in most cases. 
TimePerSlice <- data$ElapsedHours / data$Slice
TimePerSlice <- TimePerSlice[!is.infinite(TimePerSlice)]
avgTimePerSlice <- mean(TimePerSlice)

germstats$ApproxTime <- round(germstats$Slice * round(avgTimePerSlice, 2), 2)

# now calculate some germination metrics
groups <- t50s <- mgts <- mgtses <- nseeds <- nongerms <- NULL
for(group in unique(data.long$Group)) {
  # calculate t50 for summary file
  t50 <- t50(germ.counts = germstats$GermCount[germstats$Group == group], 
             intervals = germstats$ApproxTime[germstats$Group == group], 
             method = "coolbear")
  mgt <- MeanGermTime(germ.counts = germstats$GermCount[germstats$Group == group], 
             intervals = germstats$ApproxTime[germstats$Group == group])
  mgtse <- SEGermTime(germ.counts = germstats$GermCount[germstats$Group == group], 
                      intervals = germstats$ApproxTime[germstats$Group == group])
  nseed <- sum(germstats$GermCount[germstats$Group == group])
  nongerm <- sum(is.na(data.peruid$`Germination Time (h)`[data.peruid$Group == group]))
  
  t50s <- c(t50s, t50)
  groups <- c(groups, group)
  mgts <- c(mgts, mgt)
  mgtses <- c(mgtses, mgtse)
  nseeds <- c(nseeds, nseed)
  nongerms <- c(nongerms, nongerm)
  
  # make germination graph
  pdf(paste0(rundir, "/germinationplot-", group, ".pdf"), width=7, height=5)
  graph <- FourPHFfit(germ.counts = germstats$GermCount[germstats$Group == group], 
                      intervals = germstats$ApproxTime[germstats$Group == group],
                      total.seeds = length(unique(data$UID[data$Group == group])),
                      tmax = max(germstats$ApproxTime[germstats$Group == group]))
  print(plot(graph))
  dev.off()
}

germstats.pergroup <- data.frame(Group = groups, t50 = t50s, MeanGermTime = mgts, 
                                 MeanGermTimeSE = mgtses, n = nseeds, Ungerminated = nongerms)
write.table(germstats.pergroup, file=paste0(rundir, "/germinationstats.tsv"), sep='\t', row.names=F)

cat(paste0("Statistics have been written to the directory ", rundir, "\n"))
