# process_data.R -
#
#   takes data generated by cleanup_germination_data.R and estimates germination times.
#   germination times will be written to germination-{perssed,pergroup}.tsv in the data folder.

library(dplyr)

# there is no support for directory picker under non-windows platforms
if (.Platform$OS.type == 'unix') {
  dir <- readline(prompt = "Enter directory containing output.tsv: ")
} else {
  dir <- choose.dir(getwd(), "Choose folder containing output.tsv")
}

data <- read.table(paste0(dir, "/output.tsv"), header=T)

data$dPerim <- data$ddPerim <- 0
data$Germinated <- FALSE
data$pav <- groups <- uids <- perims <- NULL

for(uid in unique(data$UID)) {
  # ds = data subset
  ds <- subset(data, UID == uid)

  # seed size is average of first 5 slices
  seedsize <- mean(ds$`Perim.`[1:5])
  
  # loop through all lines. need 4 slices reserved at the end due to how the algorithm works.
  for (i in seq(1, nrow(ds) - 4)) {
    ds$dPerim[i] <- mean(ds$`Perim.`[seq(i,i+4)]) - seedsize
  }
  
  # set delta delta perimeter (rate of change of perimeter)
  ds$ddPerim[2:nrow(ds)] <- ds$dPerim[2:nrow(ds)] - ds$dPerim[1:nrow(ds) - 1]
  ds$ddPerim[1] <- 0
  
  # loop over the values again...:\
  # we need a buffer of 14 slices.
  for (i in seq(1, nrow(ds) - 14)) {
    if (ds$dPerim[i] > 0) {
      if (all(ds$ddPerim[seq(i+1, i+10)] > 0)) {
        ds$Germinated[i] <- TRUE
        break
      }
    }
  }
  
  # replace the data with the manipulated subset
  data <- subset(data, UID != uid)
  data <- rbind(data, ds)
}

data.peruid <- data %>% 
  group_by(Group, UID) %>%
  filter(Germinated == TRUE) %>%
  arrange(ElapsedHours) %>%
  summarize(GerminationTime = ElapsedHours[1], GerminationSlice = Slice[1])

# sort data naturally
m<-regexpr('([0-9]+)$', data.peruid$UID)
data.peruid$num <- as.numeric(regmatches(data.peruid$UID, m))
data.peruid<-data.peruid[order(data.peruid$Group, data.peruid$num),]
data.peruid<-data.peruid %>% select(-num)

data.pergroup <- data.peruid %>%
  group_by(Group) %>%
  summarize(GerminationTimeSD = sd(GerminationTime,na.rm=T), GerminationTime = mean(GerminationTime))

write.table(data.peruid, file=paste0(dir, "/germination-perseed.tsv"), sep='\t', row.names=F)
write.table(data.pergroup, file=paste0(dir, "/germination-pergroup.tsv"), sep='\t', row.names=F)
