# process_data.R -
#
#   takes data generated by cleanup_germination_data.R and estimates germination times.
#   statistics will be output as tsv files in the data folder.
#   additionally, a graph indicating germination progression is generated for each group.

library(dplyr)
library(reshape2)
library(germinationmetrics)
library(zoo)
library(doParallel)
library(foreach)
library(ggplot2)
library(survival)
library(survminer)
library(readr)

detect_germination <- function(ds) {
  # figure out the imaging frequency
  TimePerSlice <- ds$ElapsedHours / ds$Slice
  TimePerSlice <- TimePerSlice[!is.infinite(TimePerSlice)]
  avgTimePerSlice <- mean(TimePerSlice)
  
  # range for averages is either 2.5 h, or 5 slices (whichever is highest)
  rollrange <- round(max(5, 2.5 / avgTimePerSlice), 0)
  
  # number of positive ddPerims is either 5 h or 10 slices
  ddprange <- round(max(10, 5 / avgTimePerSlice), 0)
  
  # we need a buffer of (ddprange + rollrange + 1) slices for germination detection
  if (nrow(ds) <= ddprange + rollrange + 1) {
    cat(paste0("Too few data points for UID ", uid, ", removing from analysis.\n"))
    return(data.frame(row.names=names(ds)))
  }

  # determine initial seed size
  seedsize <- mean(ds$`Perim.`[seq(1, rollrange)])
  
  # create moving average perimeter increase (dPerim)
  ds$dPerim <- rollapply(ds$`Perim.`, rollrange, mean, na.rm=T, align="left", partial=FALSE, fill=NA)
  ds$dPerim <- ds$dPerim - seedsize
  
  # set delta delta perimeter (rate of change of perimeter)
  ds$ddPerim[2:nrow(ds)] <- ds$dPerim[2:nrow(ds)] - ds$dPerim[1:nrow(ds) - 1]
  ds$ddPerim[1] <- 0
  
  # loop over the values again...:\
  # we need a buffer of (4 + lookahead_slices) slices.
  for (i in seq(1, nrow(ds) - (rollrange + ddprange + 1))) {
    if (ds$dPerim[i] > 0) {
      if (all(ds$ddPerim[seq(i + 1, i + ddprange)] > 0)) {
        ds$Germinated[i] <- TRUE
        break
      }
    }
  }
  
  ds$Seedsize <- seedsize

  return(ds)
}

# there is no support for directory picker under non-windows platforms
if (.Platform$OS.type == 'unix') {
  dir <- readline(prompt = "Enter directory: ")
} else {
  dir <- choose.dir(getwd(), "Choose folder to process")
}

resultsdir <- paste0(dir, '/Results')
outdir <- paste0(resultsdir, '/Germination')

# set up output dir
if (dir.exists(paste0(outdir, '/Analysis output'))) {
  runs <- list.dirs(paste0(outdir, '/Analysis output'), full.names=F, recursive=F)
  run_number <- length(runs) + 1
  while (file.exists(paste0(outdir, '/Analysis output/', run_number))) {
    run_number <- run_number + 1
  }
} else {
  dir.create(paste0(outdir, '/Analysis output'), recursive=T)
  run_number <- 1
}

rundir <- paste0(outdir, '/Analysis output/', run_number)
dir.create(rundir, showWarnings=F)

if (file.exists(paste0(outdir, "/germination.postQC.tsv"))) {
  data <- read_tsv(paste0(outdir, "/germination.postQC.tsv"))
} else {
  stop("germination.postQC.tsv not found in specified directory. Did you run cleanup_germination_data.R?\n")
}

# copy postQC input file to rundir for reference
file.copy(paste0(outdir, "/germination.postQC.tsv"), rundir)
if (file.exists(paste0(outdir, "/germination.postQC.log.tsv"))) {
  file.copy(paste0(outdir, "/germination.postQC.log.tsv"), rundir)
}

data$dPerim <- data$ddPerim <- 0
data$Germinated <- 0
data$pav <- groups <- uids <- perims <- NULL

if (!exists("germination.debug")) {
  num_cores <- max(1, detectCores() - 1)
  cl <- makeCluster(num_cores)
  registerDoParallel(cl)
  
  if (num_cores > 1) {
    core_plural <- 'threads'
  } else {
    core_plural <- 'thread'
  }
  
  cat(paste0("Processing germination data, using ", 
             length(cl), ' ', core_plural, ". This may take a little while...\n"))
  
  processed_data <- foreach(uid=unique(data$UID),
                            .combine=rbind,
                            .multicombine=T,
                            .packages='zoo') %dopar% detect_germination(data[data$UID == uid,])
  stopCluster(cl)
} else {
  # set the variable germination.debug to enable single-threaded execution
  processed_data <- NULL
  for (uid in unique(data$UID)) {
    processed_data <- rbind(processed_data, detect_germination(data[data$UID == uid,]))
  }
}

data <- processed_data

data.peruid <- data %>%
  group_by(Group, UID) %>%
  filter(Germinated == 1) %>%
  arrange(ElapsedHours) %>%
  summarize(GerminationTime = ElapsedHours[1], GerminationSlice = Slice[1], SeedSize = Seedsize)

seedsizes <- data %>%
  group_by(Group) %>%
  summarize(SeedSize = mean(Seedsize, na.rm=T), SeedSizeSD = sd(Seedsize, na.rm=T))

data.peruid <- as.data.frame(data.peruid)

uids <- unique(data$UID)
uids <- uids[order(uids)]
included <- uids %in% data.peruid$UID
for(uid in uids[!included]) {
  group <- data$Group[data$UID == uid][1]
  row = data.frame(Group = group, UID = uid, GerminationTime = NA, GerminationSlice = NA, SeedSize = NA)
  data.peruid <- rbind(data.peruid, row)
}

# sort data naturally
m <- regexpr('_([0-9]+)_exp:.*$', data.peruid$UID)
data.peruid$num <- as.numeric(regmatches(data.peruid$UID, m))
data.peruid <- data.peruid[order(data.peruid$Group, data.peruid$num),]
data.peruid <- data.peruid %>% select(-num)

names(data.peruid)[3] <- 'Germination Time (h)'
names(data.peruid)[4] <- 'Germination Detected on Frame'
names(data.peruid)[5] <- 'Seed Size (cm2)'

# combine with QC notes
if (file.exists(paste0(outdir, "/germination.postQC.log.tsv"))) {
  seedlog <- read.table(paste0(outdir, "/germination.postQC.log.tsv"), header=T, stringsAsFactors=F)
  data.peruid <- merge(data.peruid, seedlog, all=T)
  write.table(data.peruid, file=paste0(rundir, "/germination-perseed.tsv"), sep='\t', row.names=F)
} else {
  data.peruid$Note <- NA
}

# merge group and uid so we can keep both in the conversion long->wide->long
data$GroupUID<-paste(data$Group, data$UID, sep="!")

# convert to wide and back again as a hacky way of making sure all seeds have equal number of slices
data.wide <- dcast(data, Slice ~ GroupUID, value.var = "Germinated")
data.long <- melt(data.wide, id.vars="Slice")

# now get all the groups and uids back
groupuids <- unlist(strsplit(as.character(data.long$variable), "!"))
data.long$Group <- groupuids[seq(1, length(groupuids), 2)]
data.long$UID <- groupuids[seq(2, length(groupuids), 2)]
data.long$value[is.na(data.long$value)] <- 0

# calculate germination stats
germstats <- data.long %>% 
  group_by(Group, Slice) %>% 
  summarize(GermCount = sum(value))

germstats <- germstats %>% 
  group_by(Group) %>%
  arrange(Slice) %>%
  mutate(CumGermCount = cumsum(GermCount))

# to get the intervals in hours, we calculate average time per slice and multiply
# slice# by that values. this will hopefully be good enough approximation in most cases. 
TimePerSlice <- data$ElapsedHours / data$Slice
TimePerSlice <- TimePerSlice[!is.infinite(TimePerSlice)]
avgTimePerSlice <- mean(TimePerSlice)

germstats$ApproxTime <- round(germstats$Slice * round(avgTimePerSlice, 2), 2)

# now calculate some germination metrics
groups <- t50s <- mgts <- mgtses <- nseeds <- nongerms <- NULL
dir.create(paste0(rundir, "/Germination Plots"))
for(group in unique(data.long$Group)) {
  # calculate t50 for summary file
  t50 <- t50(germ.counts = germstats$GermCount[germstats$Group == group], 
             intervals = germstats$ApproxTime[germstats$Group == group], 
             method = "coolbear")
  mgt <- MeanGermTime(germ.counts = germstats$GermCount[germstats$Group == group], 
             intervals = germstats$ApproxTime[germstats$Group == group])
  mgtse <- SEGermTime(germ.counts = germstats$GermCount[germstats$Group == group], 
                      intervals = germstats$ApproxTime[germstats$Group == group])
  nseed <- sum(germstats$GermCount[germstats$Group == group])
  nongerm <- sum(is.na(data.peruid$`Germination Time (h)`[which(data.peruid$Group == group)]))
  
  t50s <- c(t50s, t50)
  groups <- c(groups, group)
  mgts <- c(mgts, mgt)
  mgtses <- c(mgtses, mgtse)
  nseeds <- c(nseeds, nseed)
  nongerms <- c(nongerms, nongerm)
  
  # make germination graph
  pdf(paste0(rundir, "/Germination Plots/germinationplot-", group, ".pdf"), width=7, height=5)
  tryCatch(graph <- FourPHFfit(germ.counts = germstats$GermCount[germstats$Group == group], 
                      intervals = germstats$ApproxTime[germstats$Group == group],
                      total.seeds = length(unique(data$UID[data$Group == group])),
                      tmax = max(germstats$ApproxTime[germstats$Group == group])),
           error=function(e) {
             cat(paste0("Unable to generate germination plot for group ", group, ":\n"))
             cat(paste0(e$message, "\n"))
           })
  print(plot(graph) + labs(x="Time (h)"))
  dev.off()
}

germstats.pergroup <- data.frame(Group = groups, t50 = t50s, MeanGermTime = mgts, 
                                 MeanGermTimeSE = mgtses, n = nseeds, Ungerminated = nongerms)
germstats.pergroup <- merge(germstats.pergroup, seedsizes)
names(germstats.pergroup) <- c('Group', 't50 (h)', 'Mean Germination Time (h)', 'Mean Germination Time SE',
                               'Germinated seeds', 'Ungerminated seeds', 'Seed Size (cm2)', 'Seed Size SD')
write.table(germstats.pergroup, file=paste0(rundir, "/descriptive_stats.tsv"), sep='\t', row.names=F)

if (length(unique(data.long$Group)) > 1) {
  # generate table for t-tests
  pvals <- as.data.frame(t(combn(unique(data.long$Group), 2)))
  colnames(pvals) <- c('Group.1', 'Group.2')
  pvals$Group.1 <- as.character(pvals$Group.1)
  pvals$Group.2 <- as.character(pvals$Group.2)
  germination.pvals <- seedsize.pvals <- pvals
  
  for (i in seq(1, nrow(pvals))) {
    # first we check the p value
    tryCatch({tg <- t.test(data.peruid$`Germination Time (h)`[data.peruid$Group == pvals$Group.1[i]],
                           data.peruid$`Germination Time (h)`[data.peruid$Group == pvals$Group.2[i]])
              ts <- t.test(data.peruid$`Seed Size (cm2)`[data.peruid$Group == pvals$Group.1[i]],
                           data.peruid$`Seed Size (cm2)`[data.peruid$Group == pvals$Group.2[i]])
              germination.pvals$p.value[i] <- tg$p.value
              seedsize.pvals$p.value[i] <- ts$p.value
             },
             error=function(e) {
                cat(paste0("Unable to compare groups ", pvals$Group.1[i], "(x) to ", pvals$Group.2[i], "(y): "))
                cat(paste0(e$message, "\n"))
                germination.pvals$p.value[i] <- NA
                seedsize.pvals$p.value[i] <- NA
    })
  }
  
  # generate corrected p-values according to the false discovery rate (fdr) method
  # see help(p.adjust) for available methods
  germination.pvals$corrected.p.value <- p.adjust(germination.pvals$p.value, method="fdr")
  seedsize.pvals$corrected.p.value <- p.adjust(seedsize.pvals$p.value, method="fdr")
  
  names(germination.pvals) <- c('Group 1', 'Group 2', 'Raw p value', 'FDR-corrected p value')
  write.table(germination.pvals, file=paste0(rundir, "/germination.t-tests.tsv"), sep='\t', row.names=F)
  write.table(seedsize.pvals, file=paste0(rundir, "/seedsize.t-tests.tsv"), sep='\t', row.names=F)
} else {
  cat("Only one group in output, skipping t-tests.\n")
}

if (length(unique(data.long$Group)) > 1) {
  dir.create(paste0(rundir, "/Kaplan-Meier Plots"))
  # generate table for kaplan-meier plots
  # we only compare two groups for each analysis -- 
  #   please make your own custom analysis if this is inappropriate for your data!
  pvals$km.logrank <- NA
  
  # include only seeds that were processed normally or status is unknown (i.e., log file missing)
  data.surv <- data.peruid[data.peruid$Note=='Seed processed normally.' | is.na(data.peruid$Note),]

  data.surv$event <- 1
  data.surv$event[which(is.na(data.surv$`Germination Time (h)`))] <- 0
  # ungerminated seeds have a 0 for event and a time equal to end of assay
  data.surv$`Germination Time (h)`[which(is.na(data.surv$`Germination Time (h)`))] <- max(data$ElapsedHours)

  # make a kaplan-meier plot for all groups
  survobj <- Surv(time=data.surv$`Germination Time (h)`, event=data.surv$event)
  sfit <- survfit(survobj~Group, data=data.surv)
  p <- ggsurvplot(sfit, pval=F, fun=function(y) { return(1-y) }) +
    labs(x='Elapsed Time (h)', y='Fraction of germinated seeds')
  suppressWarnings(ggsave(p$plot, 
                          filename=paste0(rundir, "/Kaplan-Meier Plots/KaplanMeier-allgroups.pdf"), 
                          width=25, height=15, units="cm"))
  
  for (i in seq(1, nrow(pvals))) {
    ds <- data.surv %>% filter(Group == pvals$Group.1[i] | Group == pvals$Group.2[i])
    survobj <- Surv(time=ds$`Germination Time (h)`, event=ds$event)
    sfit <- survfit(survobj~Group, data=ds)
    p <- ggsurvplot(sfit, pval=F, fun=function(y) { return(1-y) }) +
      labs(x='Elapsed Time (h)', y='Fraction of germinated seeds')
    suppressWarnings(ggsave(p$plot, 
                            filename=paste0(rundir, "/Kaplan-Meier Plots/KaplanMeier-", pvals$Group.1[i], "_vs_", pvals$Group.2[i], ".pdf"), 
                            width=25, height=15, units="cm"))
    # get p-value (standard log-rank)
    pvals$km.logrank[i] <- surv_pvalue(sfit)$pval
  }
  names(pvals) <- c('Group 1', 'Group 2', 'Log-Rank p-value')
  write.table(pvals, file=paste0(rundir, "/germination.kaplan-meier_test.tsv"), sep='\t', row.names=F)
}

cat(paste0("Statistics have been written to the directory ", rundir, "\n"))
